stages:
  - build
  - gitops
  - delivery

build-main-job:
  stage: build
  only:
    - tags
  except:
    - branches
  script:
    - |
      docker build . \
        -t $DOCKER_REGISTORY_URL/tingtt/slidev/$(git branch --contains tags/$CI_COMMIT_TAG | grep -v HEAD | xargs):latest \
        -t $DOCKER_REGISTORY_URL/tingtt/slidev/$(git branch --contains tags/$CI_COMMIT_TAG | grep -v HEAD | xargs):$(echo $CI_COMMIT_TAG | cut -d '/' -f 2)

push-tags-job:
  stage: build
  only:
    - tags
  except:
    - branches
  needs:
    - build-main-job
  script:
    - docker push $DOCKER_REGISTORY_URL/tingtt/slidev/$(git branch --contains tags/$CI_COMMIT_TAG | grep -v HEAD | xargs):$(echo $CI_COMMIT_TAG | cut -d '/' -f 2)

sync-github:
  stage: delivery
  before_script:
    - git config --local user.name "$GITHUB_USER"
    - git config --local user.email "$GITHUB_EMAIL"
    - git remote add github https://$GITHUB_USER:$GITHUB_ACCESS_TOKEN@github.com/tingtt/slidev.git || true
  script:
    - git checkout $CI_COMMIT_REF_NAME
    - git pull origin $CI_COMMIT_REF_NAME -r
    - git push github $CI_COMMIT_REF_NAME -f --tags
